### PR TITLE
Make it work on stable

### LINKED ISSUE #34: Doesn't compile on stable
Rustup:

```
$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.27.1 (5f2b325f6 2018-07-07)
```

Cargo output:

```
error[E0554]: #![feature] may not be used on the stable release channel
 --> /Users/maxyankov/.cargo/registry/src/github.com-1ecc6299db9ec823/mockers-0.12.0/src/lib.rs:1:1
  |
1 | / #![feature(fnbox, inclusive_range_methods, alloc, collections_range,
2 | |            inclusive_range, inclusive_range_fields, specialization)]
  | |____________________________________________________________________^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `mockers`.
```

My cargo.toml:
```
[dependencies]
mockers_derive = "0.12.0"

[dev-dependencies]
mockers = "0.12.0"
```

My lib.rs:

```
#![feature(proc_macro)]
#[cfg(test)] extern crate mockers;
#[cfg(test)] extern crate mockers_derive;
```

### PR DESCRIPTION
**Pull request by mcarton**
While the guide specifies

> Mockers uses `proc_macro` feature, so it works with both nightly and stable compiler.

This wasn't actually true, because of few other features were used. It turns out it is easy to avoid them:

- `fnbox` could be replaced with `impl Trait` for most of them, and a specialized trait for the rest.
- `specialization` is only used for convenience features: it makes non-`Debug` types work, but this is not essential as most types are `Debug`. This can be re-enabled with the `nightly` feature.
- `proc_macro_diagnostic` is also only used for convenience: It improves error messages. Not required most of the time. This can be re-enabled with the `nightly` feature.

I started this PR by factoring all duplicated code into a few macros. This made the rest easier to refactor. It would also make it easy to enable the use of more that 4 parameters per function.

Closes #34.

### CODE REVIEW

**Comment by kriomant** [comment]
It is just great! I've started to review changes, it may take a while.

File: mockers/src/lib.rs [hunk 1]
```diff
@@ -8,6 +8,8 @@ use std::rc::{Rc, Weak};
 use std::fmt::Write;
 use std::ops::DerefMut;
 
+use itertools::Itertools;
```
Comment (kriomant) [inline mockers/src/lib.rs]: What do you use from itertools?

**Comment by kriomant** [comment]
You've made an incredible work! Thank you. There are only small cosmetic issues I would like to have fixed.

Seems you use mockers in your project (why put so large effort otherwise?) Can you share your experience about working with my library?

I also have some pending code changes and some plans and I would like to share and discuss them with someone interested. Contact me by email:kriomant@gmail.com / telegram:kriomant / anything you uses if you want to participate.

File: mockers/src/lib.rs (hunk 1 above)
Comment (mcarton) [reply mockers/src/lib.rs]: Describe was implemented as:

```rust
fn describe(&self) -> String {
    format!(
        "{}({}, {})",
        self.get_method_name(),
        self.arg0.describe(),
        self.arg1.describe()
    )
```
(with different number of `argN`s for each type)

Now it is

```rust
fn describe(&self) -> String {
    let args: &[&std::fmt::Display] = &[$(&self.$arg.describe()),*];
    format!("{}({})", self.get_method_name(), args.iter().format(", ")) 
}
```

Where `format` comes from itertool. It could be avoided by making the macro a bit more complex, but given that `mockers_derive` already depended on `itertools`, I didn't see that new dependency as a big deal. (Although right now `mockers` and `mockers_derive` don't use the same version of `itertools`, but I wanted feedback on this PR before suggesting any more change).

**Comment by mcarton** [comment]
> You've made an incredible work! Thank you. There are only small cosmetic issues I would like to have fixed.

Such as?

> Seems you use mockers in your project (why put so large effort otherwise?) Can you share your experience about working with my library?

I have not been using `mockers` extensively yet, but my company is planning to use Rust for a new project, and I was making a pre-study on mocking libraries for Rust. `mockers` was one of the best one and most complete one I tested, but requiring `nightly` was a no-go for us. If this PR gets merged, it will be the one I will recommend.

> I also have some pending code changes and some plans and I would like to share and discuss them with someone interested.

I have limited time, but I could talk about future plans.
